### ISSUE TITLE
not work in xcode 7.2

### ISSUE THREAD

**Issue by sumitmundra** [julian-weinert/CrashSymbal#1]
hello ,

its not work on xcode 7.2 plz chk.

**Comment by julian-weinert** [comment]
Should be working now; fixed in https://github.com/julian-weinert/CrashSymbal/commit/db0514bf805f9c8e42348eacaee40feafa86e8c0

**Comment by julian-weinert** [comment]
@sumitmundra can you please confirm?

**Comment by sumitmundra** [comment]
![screen shot 2015-12-28 at 10 50 21 am](https://cloud.githubusercontent.com/assets/4879986/12014346/f35f71f6-ad50-11e5-9aa6-b6eddbf379ee.png)

not show crash symbol menu in debug menu

**Comment by julian-weinert** [comment]
Okay, I'll investigate here...

**Comment by julian-weinert** [comment]
@sumitmundra sorry for leaving this untouched for so long.
I'd like to go into it, but I won't get a version of 7.2 running at the moment.

Could you please check that again and confirm the compatibility UUID of your Xcode installation is not in your current versions `Info.plist` of CrashSymbal?
